// Code generated by "stringer -type=CharTypeID"; DO NOT EDIT.

package aozoraconvert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Symbol-1]
	_ = x[Hiragana-2]
	_ = x[Katakana-4]
	_ = x[Kanji-8]
	_ = x[Whitespace-16]
	_ = x[Punctuation-32]
	_ = x[Roman-64]
}

const (
	_CharTypeID_name_0 = "SymbolHiragana"
	_CharTypeID_name_1 = "Katakana"
	_CharTypeID_name_2 = "Kanji"
	_CharTypeID_name_3 = "Whitespace"
	_CharTypeID_name_4 = "Punctuation"
	_CharTypeID_name_5 = "Roman"
)

var (
	_CharTypeID_index_0 = [...]uint8{0, 6, 14}
)

func (i CharTypeID) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _CharTypeID_name_0[_CharTypeID_index_0[i]:_CharTypeID_index_0[i+1]]
	case i == 4:
		return _CharTypeID_name_1
	case i == 8:
		return _CharTypeID_name_2
	case i == 16:
		return _CharTypeID_name_3
	case i == 32:
		return _CharTypeID_name_4
	case i == 64:
		return _CharTypeID_name_5
	default:
		return "CharTypeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
