// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package aozoraconvert

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[emptyToken-0]
	_ = x[textToken-1]
	_ = x[gaijiToken-2]
	_ = x[rubyGroupStartToken-3]
	_ = x[rubyGroupEndToken-4]
	_ = x[rubyParentStartToken-5]
	_ = x[rubyParentEndToken-6]
	_ = x[rubyStartToken-7]
	_ = x[rubyEndToken-8]
	_ = x[noteToken-9]
	_ = x[bibInfoToken-10]
	_ = x[bibInfoEndToken-11]
	_ = x[emptyLineToken-12]
	_ = x[endOfLineToken-13]
	_ = x[paragraphEndToken-14]
	_ = x[paragraphToken-15]
	_ = x[sectionTitleStartToken-16]
	_ = x[sectionTitleEndToken-17]
	_ = x[sectionToken-18]
	_ = x[subsectionToken-19]
	_ = x[subsubsectionToken-20]
	_ = x[sectionEndToken-21]
	_ = x[subsectionEndToken-22]
	_ = x[subsubsectionEndToken-23]
	_ = x[figureStartToken-24]
	_ = x[figureEndToken-25]
	_ = x[gaijiNoteToken-26]
	_ = x[specialCharToken-27]
	_ = x[accentStartToken-28]
	_ = x[accentEndToken-29]
	_ = x[gaijiCharToken-30]
	_ = x[kunojiToken-31]
	_ = x[alignBottomCloserToken-32]
	_ = x[centeringEndToken-33]
	_ = x[markupNoteToken-34]
	_ = x[mainTextStartToken-35]
	_ = x[mainTextEndToken-36]
	_ = x[eofToken-37]
	_ = x[gaijiImgToken-38]
	_ = x[noteStartToken-39]
	_ = x[noteEndToken-40]
	_ = x[gaijiStartToken-41]
	_ = x[endMarkerToken-42]
}

const _tokenType_name = "emptyTokentextTokengaijiTokenrubyGroupStartTokenrubyGroupEndTokenrubyParentStartTokenrubyParentEndTokenrubyStartTokenrubyEndTokennoteTokenbibInfoTokenbibInfoEndTokenemptyLineTokenendOfLineTokenparagraphEndTokenparagraphTokensectionTitleStartTokensectionTitleEndTokensectionTokensubsectionTokensubsubsectionTokensectionEndTokensubsectionEndTokensubsubsectionEndTokenfigureStartTokenfigureEndTokengaijiNoteTokenspecialCharTokenaccentStartTokenaccentEndTokengaijiCharTokenkunojiTokenalignBottomCloserTokencenteringEndTokenmarkupNoteTokenmainTextStartTokenmainTextEndTokeneofTokengaijiImgTokennoteStartTokennoteEndTokengaijiStartTokenendMarkerToken"

var _tokenType_index = [...]uint16{0, 10, 19, 29, 48, 65, 85, 103, 117, 129, 138, 150, 165, 179, 193, 210, 224, 246, 266, 278, 293, 311, 326, 344, 365, 381, 395, 409, 425, 441, 455, 469, 480, 502, 519, 534, 552, 568, 576, 589, 603, 615, 630, 644}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
